spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jooq?characterEncoding=utf8&useSSL=true
    username: root
    password:
    useSSL: true
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org:.jooq: DEBUG